CC=mpiicx
FC=mpiifx

BASE_CFLAGS = -g -O3 -fiopenmp -march=native -mprefer-vector-width=512

CFLAGS=$(BASE_CFLAGS) ${LIKWID_INCLUDE} -DLIKWID -DLIKWID_PERFMON
VCFLAGS += ${LIKWID_INCLUDE} -DLIKWID -DLIKWID_PERFMON
LDFLAGS = ${LIKWID_LIB} -llikwid
